= Deploy App to OpenShift with Helm - Instructions
:imagesdir: ../assets/images/

++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XS54W2D18Q"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XS54W2D18Q');
</script>
<style>
  .nav-container, .pagination, .toolbar {
    display: none !important;
  }
  .doc {    
    max-width: 70rem !important;
  }
</style>
++++

== 1. Streamline App Deployment on OpenShift with Helm

Helm acts like a software package manager for applications you run on OpenShift Container Platform, similar to app stores on your phone. It simplifies deployment by using pre-configured packages called Helm charts.

* *Helm Charts*: These reusable packages bundle all the configuration files needed for a Kubernetes application.
* *Deployment Made Easy*: With Helm, you can install, upgrade, and manage your applications efficiently.
* *Version Control*: Helm charts can be versioned, allowing you to track changes and revert to previous configurations if needed.

When you deploy a Helm chart, you create a running instance called a release. Helm also keeps track of revisions whenever you upgrade or roll back a release, giving you control over your application's history.

Helm charts offer several key benefits that streamline application deployment and management in Kubernetes environments:

* *Increased Productivity*: Helm charts act as pre-packaged applications, eliminating the need to manually write individual YAML files for each deployment. This saves developers significant time and effort.
* *Simplified Deployments*: Helm charts standardize deployments by encapsulating all the necessary configuration files and resources within a single unit. This simplifies the deployment process and reduces the risk of errors.
* *Improved Configurability*: Helm charts often come with default configurations that can be overridden with custom values during deployment. This allows for easy adaptation to different environments and user requirements.
* *Enhanced Repeatability*: Deployments performed using Helm charts are guaranteed to be identical each time, leading to more consistent and reliable deployments.
* *Streamlined Rollbacks*: In case of issues, Helm allows for easy rollbacks to previous versions of the application with a single command. This minimizes downtime and simplifies troubleshooting.
* *Version Control*: Helm charts can be versioned alongside your application code, ensuring consistency between deployments and your development process.
* *Community and Reusability*: A vast repository of Helm charts exists, allowing you to leverage pre-built charts for commonly used applications or create your own and share them with the community.

=== 1.1. Build and deploy a new Java application using Helm

In this module, you will deploy a new Java application using Helm. The application is a simple to-do list manager built with Quarkus, a Kubernetes-native Java framework. You will use Helm to streamline the deployment process and create a running instance of the application on OpenShift.

== 2. Deploy Globex Coolstore app using Helm


Please close all but the Workshop Deployer browser tab to avoid proliferation of browser tabs which can make working on other modules difficult. 

Go back to the `Workshop Deployer` browser tab to choose your next module!

[.console-input]
[source,yaml,subs="+attributes,macros+"]
----
build:
  enabled: true
  jvm:
    imageStreamTag:
      name: 'java:openjdk-17-ubi8'
      namespace: openshift
  mode: jvm
  uri: 'https://github.com/rh-mad-workshop/quarkus-todo-app.git'
deploy:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  replicas: 1
  route:
    enabled: true
    targetPort: http
    tls:
      enabled: true
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
  serviceType: ClusterIP
----


[.console-input]
[source,yaml,subs="+attributes,macros+"]
----
  livenessProbe:
    tcpSocket:
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  replicas: 2
----