= Migration to JBoss EAP - Intro
:imagesdir: ../assets/images/

++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-M2B2QW31FT"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-M2B2QW31FT');
</script>
<style>
  .nav-container, .pagination, .toolbar {
    display: none !important;
  }
  .doc {    
    max-width: 70rem !important;
  }
</style>
++++

The story so far: Globex has been in business for several years with a core retail application written for a proprietary, expensive app server. They are now all-in on modernization to save costs and update to newer, open source products.

In this exercise you will use https://developers.redhat.com/products/mta/overview[Migration Toolkit for Applications^] (based on the CNCF https://www.konveyor.io/[Konveyor project^]) to helps modernize applications by providing open source tools to rehost, replatform, and refactor applications to Kubernetes and cloud-native technologies.

Ease the adoption of Red Hat OpenShift or Red Hat Application Foundations with the Migration Toolkit for Applications. With ontainerization-readiness, source-code analysis, and project management capabilities this tool can help your organization benefit from faster, safer legacy application modernization.

Key benefits of the Migration Toolkit for Applications include:

* Get guidance throughout the modernization process
* Benefit from faster, safer modernization
* Avoid a locked-in mindset

Proceed to the xref:./module-eap-instructions.adoc[instructions] for this module.