= Day 2 operations with Ansible MiddleWare - Instructions
:imagesdir: ../assets/images/

++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-L6CY091CT6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-L6CY091CT6');
</script>
<style>
  .nav-container, .pagination, .toolbar {
    display: none !important;
  }
  .doc {    
    max-width: 70rem !important;
  }
</style>
++++

Story: Globex has been in business for several years with a core retail EAP application running on-prem in VMs. They struggle to respond on time when issues come up and spend a lot of time keeping their servers up to date with newer versions or patches. They are looking to automate many of the manual administrative tasks they do each day. 

Please close all but the Workshop Deployer browser tab to avoid proliferation of browser tabs which can make working on other modules difficult. 

Proceed to the https://workshop-deployer.{openshift_subdomain}[Workshop Deployer] to choose your next module.