= Outerloop with OpenShift Pipelines and GitOps - Intro
:imagesdir: ../assets/images/

++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XNR5N131B9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XNR5N131B9');
</script>
<style>
  .nav-container, .pagination, .toolbar {
    display: none !important;
  }
  .doc {    
    max-width: 70rem !important;
  }
</style>
++++

The story so far: Globex has been growing quickly thanks to the success of its modernized business applications. However, they have recently experienced several production issues, and after root cause analysis, determined it’s due to unexpected dependencies getting upgraded during builds and admins making out-of-band configuration changes with unexpected consequences. They want to improve how they build, test, and deliver their applications.

In this exercise you will use `OpenShift Pipelines`, a cloud-native continuous integration and continuous delivery (CI/CD) solution built on Kubernetes. It provides a framework for automating the building, testing, and deploying of containerized applications. In addtion, you will learn how you can use OpenShift Pipelines to automate the `GitOps` workflow with Argo CD. By combining *OpenShift Pipelines with GitOps*, developers can achieve a more automated, reliable, and efficient workflow for deploying and managing cloud-native applications.

Let's start the workshop with the discovery of OpenShift and OpenShift Dev Spaces.

Proceed to the xref:./module-outerloop-instructions.adoc[instructions] for this module.