= Service Interconnect - Instructions
:imagesdir: ../assets/images/

++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WJJ9SY6RSW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WJJ9SY6RSW');
</script>
<style>
  .nav-container, .pagination, .toolbar {
    display: none !important;
  }
  .doc {    
    max-width: 70rem !important;
  }
</style>
++++

Story: As part of Globex’s multi-year modernization initiative, they have adopted OpenShift and have migrated many of their applications to it, however, several backend systems remain in place due to data sovereignty laws and technical limitations of their cloud provider. They want to be able to securely connect their cloud applications with the backend, without a lot of work for their developers, who aren’t as security-aware as the product security team.

Please close all but the Workshop Deployer browser tab to avoid proliferation of browser tabs which can make working on other modules difficult. 

Go back to the `Workshop Deployer` browser tab to choose your next module! to choose your next module.