= Accelerating Software development with RH Developer Hub - Intro
:imagesdir: ../assets/images/

++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-9HZBMQ1K32"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-9HZBMQ1K32');
</script>
<style>
  .nav-container, .pagination, .toolbar {
    display: none !important;
  }
  .doc {    
    max-width: 70rem !important;
  }
</style>
++++

The story so far: Globex has been growing quickly thanks to the success of its modernized business applications. However, the time to market for new applications has not improved as much as they’d like. They suspect this is due to hiring many new developers to expand their business offerings, but with inconsistent policies, lack of automation, and lack of developer guidance across different lines of business when they start and manage new projects.

In this exercise you will build, deploy, and manage applications using https://developers.redhat.com/rhdh/overview[Red Hat Developer Hub^] that allows you to perform the Software Development activities with an accelerated approach by reducing developer friction and improving time to market.

The module starts with the product overview, followed by its architecture and a tour of the main functionalities. You will implement two use cases, from *maintaining a new application* that requires bug fixing to *modernizing a set of microservices* by moving them into OpenShift.

Key benefits of the Red Hat Developer Hub include:

* *Increased Developer Productivity*: Automate many tasks, freeing developers to focus on core coding activities. Pre-built components and templates further streamline development.
* *Improved Onboarding*:  New team members can get up and running quickly with access to common tools, services, and best practices through a central platform.
* *Enhanced Collaboration*: The Hub fosters a collaborative environment by allowing teams to share tools and resources across projects, ensuring consistency and efficiency.
* *Reduced Cognitive Load*: By providing a single, unified platform, Red Hat Developer Hub reduces the number of tools and resources developers need to manage, minimizing confusion and wasted effort.
* *Faster Time to Market*: Streamlined workflows, pre-built components, and automated tasks lead to faster application development and deployment.
* *Enterprise-Grade Support*:  Red Hat provides ongoing support for both the Developer Hub platform itself and the Red Hat plugins that integrate with it, ensuring stability and reliability.
* *Flexibility and Openness*: Based on the open-source Backstage platform, Red Hat Developer Hub avoids vendor lock-in, allowing for customization and integration with other tools.

Proceed to the xref:./module-devhub-instructions.adoc[instructions] for this module.